[package]
name = "ffi_tester"
version = "0.1.0"
edition = "2024"

[lib]
name = "ffi_tester"
crate-type = ["staticlib"]

[dependencies]
arrow = { git = "https://github.com/steelcake/arrow-rs", features = ["ffi"] }
